/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_edu_nuc_androidlab_opencvdemo_JNIUtils */

#ifndef _Included_cn_edu_nuc_androidlab_opencvdemo_JNIUtils
#define _Included_cn_edu_nuc_androidlab_opencvdemo_JNIUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_edu_nuc_androidlab_opencvdemo_JNIUtils
 * Method:    getEdge
 * Signature: (Ljava/lang/Object;)[I
 */
JNIEXPORT jintArray JNICALL Java_cn_edu_nuc_androidlab_opencvdemo_JNIUtils_getEdge
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
