/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class androidlab_edu_cn_nucyixue_utils_JNIUtils */

#ifndef _Included_androidlab_edu_cn_nucyixue_utils_JNIUtils
#define _Included_androidlab_edu_cn_nucyixue_utils_JNIUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     androidlab_edu_cn_nucyixue_utils_JNIUtils
 * Method:    getEdge
 * Signature: (Ljava/lang/Object;)[I
 */
JNIEXPORT jintArray JNICALL Java_androidlab_edu_cn_nucyixue_utils_JNIUtils_getEdge
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
